Repository antoinemansour7/miniCap, pull requests merged in 2025-03, with the labels that each got.

#176 Location selector UI crash fixed
  FindMyClass/app/screens/directions.jsx
  FindMyClass/components/directions/LocationSelector.js
Labels: bug, enhancement

#170 Feature/2.0 differentiation of paths in public transportation mode
  FindMyClass/app/__tests__/DirectionsScreen.test.js
  FindMyClass/app/screens/directions.jsx
Labels: enhancement

#188 Profile Editing Feature
  FindMyClass/app/__tests__/profile.test.js
  FindMyClass/app/screens/profile.jsx
  FindMyClass/jest.setup.js
Labels: enhancement, design, frontend, backend
